version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run: cd cmd/prg && go get .
      - run: make clean
      - run: make
      - run: bin/test_acceptance

    working_directory: /go/src/github.com/monokrome/progress
